[package]
name = "pcapraven-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "=0.4.13" }
pcapraven-pcap = { path = "../crates/pcapraven-pcap", version = "0.0.0" }

[[bin]]
name = "fuzz_pcap_reader"
path = "fuzz_targets/fuzz_pcap_reader.rs"
test = false
doc = false
bench = false
